# Generated by Django 5.1.3 on 2024-11-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inst_name', models.CharField(max_length=40)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('status', models.CharField(default='pending', max_length=12)),
                ('phone', models.CharField(default='null', max_length=12)),
                ('registration_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('established_date', models.DateField(blank=True, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('number_of_students', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
