# Generated by Django 5.1.3 on 2024-11-14 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_qualification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_of_experience', models.IntegerField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='principal/')),
                ('certifications', models.CharField(blank=True, max_length=255, null=True)),
                ('professional_summary', models.TextField(blank=True, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('institute', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.institute')),
                ('qualifications', models.ManyToManyField(related_name='principals', to='account.qualification')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Principal',
                'verbose_name_plural': 'Principals',
            },
        ),
    ]
